#!/usr/bin/env python3
"""
Run the v5 StatsPAI staggered DID examples directly from StatsPAI outputs.

This script mirrors the code blocks in the v5 article and saves results to:

    outputs/v5_statspai_direct/
    figures/v5_statspai_direct/

The event-study / parallel-trend figures are generated by StatsPAI result
objects via ``result.event_study_plot()``. There is intentionally no fallback
plotting implementation in this script.
"""

from __future__ import annotations

import json
import os
import platform
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = ROOT / "outputs" / "v5_statspai_direct"
FIGURE_DIR = ROOT / "figures" / "v5_statspai_direct"
REQUIRED_STATSPAI = "1.16.0"
SEED = 20260530

os.environ.setdefault("NUMBA_CACHE_DIR", str(ROOT / ".cache" / "numba"))
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".cache" / "matplotlib"))
Path(os.environ["NUMBA_CACHE_DIR"]).mkdir(parents=True, exist_ok=True)
Path(os.environ["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statspai as sp


LOG_LINES: list[str] = []


def log(message: str = "") -> None:
    print(message)
    LOG_LINES.append(message)


def json_default(obj: Any) -> Any:
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, pd.DataFrame):
        return obj.to_dict(orient="records")
    if isinstance(obj, pd.Series):
        return obj.to_dict()
    return str(obj)


def round_float(value: Any, ndigits: int = 4) -> float:
    return round(float(value), ndigits)


def configure_plots() -> None:
    from matplotlib import font_manager

    preferred_fonts = [
        "PingFang SC",
        "Songti SC",
        "Heiti SC",
        "STHeiti",
        "SimHei",
        "Noto Sans CJK SC",
        "Arial Unicode MS",
    ]
    available = {font.name for font in font_manager.fontManager.ttflist}
    for font_name in preferred_fonts:
        if font_name in available:
            plt.rcParams["font.sans-serif"] = [font_name, "DejaVu Sans"]
            break

    plt.rcParams.update(
        {
            "axes.unicode_minus": False,
            "figure.dpi": 140,
            "savefig.dpi": 220,
            "font.size": 10,
        }
    )


def write_json(path: Path, payload: Any) -> None:
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, default=json_default),
        encoding="utf-8",
    )


def save_statspai_event_plot(result: Any, path: Path, title: str, color: str) -> None:
    log(f"Generating StatsPAI event-study plot: {path.relative_to(ROOT)}")
    fig, _ = result.event_study_plot(title=title, color=color)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def make_staggered_did_data(seed: int = SEED) -> pd.DataFrame:
    np.random.seed(seed)

    n_units = 800
    years = np.arange(2010, 2020)
    cohorts = np.array([0, 2013, 2014, 2015, 2016, 2017])
    probs = np.array([0.20, 0.16, 0.16, 0.16, 0.16, 0.16])

    group_assignment = np.random.choice(cohorts, size=n_units, p=probs)
    x1 = np.random.normal(0, 1, n_units)
    x2 = np.random.normal(0, 1, n_units)

    data_list: list[dict[str, Any]] = []
    for i, g in enumerate(group_assignment):
        alpha_i = np.random.normal(0, 0.7) + 0.2 * x1[i]
        for t in years:
            treatment = int(g != 0 and t >= g)
            event_time = t - g if g != 0 else np.nan

            tau = 0.0
            if treatment == 1:
                tau = 0.8 + 0.25 * event_time + 0.12 * (2017 - g)

            lambda_t = 0.15 * (t - 2010) + 0.02 * (t - 2010) ** 2 / 10
            eps = np.random.normal(0, 0.8)
            y = 5 + alpha_i + lambda_t + 0.4 * x1[i] - 0.2 * x2[i] + tau + eps

            data_list.append(
                {
                    "unit_id": i,
                    "year": t,
                    "first_treat_year": g,
                    "treatment": treatment,
                    "event_time": event_time,
                    "Y": y,
                    "X1": x1[i],
                    "X2": x2[i],
                }
            )

    return pd.DataFrame(data_list)


def save_data_tables(df: pd.DataFrame) -> None:
    df.to_csv(OUTPUT_DIR / "simulated_staggered_did_data.csv", index=False)

    cohort_distribution = (
        df.drop_duplicates("unit_id")["first_treat_year"]
        .value_counts()
        .sort_index()
        .rename_axis("first_treat_year")
        .reset_index(name="n_units")
    )
    treatment_by_year = (
        df.groupby(["year", "treatment"])["unit_id"]
        .count()
        .unstack(fill_value=0)
        .rename(columns={0: "untreated_obs", 1: "treated_obs"})
        .reset_index()
    )
    cohort_distribution.to_csv(OUTPUT_DIR / "table_cohort_distribution.csv", index=False)
    treatment_by_year.to_csv(OUTPUT_DIR / "table_treatment_by_year.csv", index=False)

    log("Data diagnostics")
    log(f"  sample size: {len(df)}")
    log(f"  units: {df['unit_id'].nunique()}")
    log(f"  periods: {df['year'].nunique()}")
    log("\nCohort distribution")
    log(cohort_distribution.to_string(index=False))
    log("\nTreatment status by year")
    log(treatment_by_year.to_string(index=False))


def save_result(name: str, result: Any) -> dict[str, Any]:
    result.tidy().to_csv(OUTPUT_DIR / f"{name}_tidy.csv", index=False)
    detail = getattr(result, "detail", None)
    if isinstance(detail, pd.DataFrame) and not detail.empty:
        detail.to_csv(OUTPUT_DIR / f"{name}_detail.csv", index=False)
    return {
        "name": name,
        "method": getattr(result, "method", name),
        "estimand": getattr(result, "estimand", ""),
        "estimate": round_float(result.estimate, 6),
        "se": round_float(result.se, 6),
        "pvalue": round_float(result.pvalue, 6),
        "ci_low": round_float(result.ci[0], 6),
        "ci_high": round_float(result.ci[1], 6),
        "n_obs": getattr(result, "n_obs", np.nan),
    }


def full_event_horizon(df: pd.DataFrame) -> tuple[int, int, list[int]]:
    rel_time = (
        df.loc[df["first_treat_year"] > 0, "year"]
        - df.loc[df["first_treat_year"] > 0, "first_treat_year"]
    )
    event_min = int(rel_time.min())
    event_max = int(rel_time.max())
    horizon = [e for e in range(event_min, event_max + 1) if e != -1]
    return event_min, event_max, horizon


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    configure_plots()

    version_info = {
        "python_version": platform.python_version(),
        "python_executable": sys.executable,
        "platform": platform.platform(),
        "statspai_version": getattr(sp, "__version__", "unknown"),
        "required_statspai_version": REQUIRED_STATSPAI,
        "numpy_version": np.__version__,
        "pandas_version": pd.__version__,
        "matplotlib_version": matplotlib.__version__,
        "seed": SEED,
    }
    write_json(OUTPUT_DIR / "version_info.json", version_info)
    log("Version information")
    for key, value in version_info.items():
        log(f"  {key}: {value}")
    if version_info["statspai_version"] != REQUIRED_STATSPAI:
        raise SystemExit(
            f"StatsPAI version must be {REQUIRED_STATSPAI}; "
            f"found {version_info['statspai_version']}"
        )

    log("\nGenerating simulated staggered DID data")
    df = make_staggered_did_data()
    save_data_tables(df)

    result_summaries: list[dict[str, Any]] = []
    plot_sources: dict[str, str] = {}

    log("\nRunning Goodman-Bacon decomposition")
    bacon = sp.bacon_decomposition(
        data=df,
        y="Y",
        treat="treatment",
        time="year",
        id="unit_id",
    )
    log(f"  TWFE estimate: {round_float(bacon['beta_twfe'], 4)}")
    log(f"  Comparisons: {bacon['n_comparisons']}")
    log(f"  Problem comparison share: {round_float(bacon['negative_weight_share'], 4)}")
    bacon["decomposition"].to_csv(OUTPUT_DIR / "bacon_decomposition.csv", index=False)
    write_json(
        OUTPUT_DIR / "bacon_summary.json",
        {
            "beta_twfe": bacon["beta_twfe"],
            "n_comparisons": bacon["n_comparisons"],
            "negative_weight_share": bacon["negative_weight_share"],
        },
    )

    log("\nRunning Callaway-Sant'Anna")
    cs = sp.callaway_santanna(
        data=df,
        y="Y",
        g="first_treat_year",
        t="year",
        i="unit_id",
        x=["X1", "X2"],
        estimator="dr",
        control_group="nevertreated",
    )
    log(str(cs))
    cs_pretrend = cs.pretrend_test()
    write_json(OUTPUT_DIR / "cs_pretrend_test.json", cs_pretrend)
    result_summaries.append(save_result("cs", cs))
    save_statspai_event_plot(
        cs,
        FIGURE_DIR / "fig04_cs_statspai_event_study.png",
        "Callaway-Sant'Anna dynamic effects",
        "#2C7FB8",
    )
    plot_sources["fig04_cs_statspai_event_study.png"] = (
        "Generated directly by cs.event_study_plot() from StatsPAI"
    )

    log("\nRunning Sun-Abraham")
    sa = sp.sun_abraham(
        data=df,
        y="Y",
        g="first_treat_year",
        t="year",
        i="unit_id",
        control_group="nevertreated",
    )
    log(str(sa))
    result_summaries.append(save_result("sa", sa))
    save_statspai_event_plot(
        sa,
        FIGURE_DIR / "fig05_sa_statspai_event_study.png",
        "Sun-Abraham event-study estimates",
        "#9C755F",
    )
    plot_sources["fig05_sa_statspai_event_study.png"] = (
        "Generated directly by sa.event_study_plot() from StatsPAI"
    )

    log("\nRunning Borusyak-Jaravel-Spiess imputation")
    event_min, event_max, bjs_horizon = full_event_horizon(df)
    log(f"  Event-study range: {event_min} to {event_max}; omitted baseline: -1")
    bjs = sp.did_imputation(
        data=df,
        y="Y",
        group="unit_id",
        time="year",
        first_treat="first_treat_year",
        controls=["X1", "X2"],
        horizon=bjs_horizon,
    )
    log(str(bjs))
    bjs_pretrend = bjs.pretrend_test()
    write_json(OUTPUT_DIR / "bjs_pretrend_test.json", bjs_pretrend)
    result_summaries.append(save_result("bjs", bjs))
    save_statspai_event_plot(
        bjs,
        FIGURE_DIR / "fig06_bjs_statspai_event_study.png",
        "BJS imputation event-study estimates",
        "#59A14F",
    )
    plot_sources["fig06_bjs_statspai_event_study.png"] = (
        "Generated directly by bjs.event_study_plot() from StatsPAI"
    )

    log("\nRunning de Chaisemartin-D'Haultfoeuille / did_multiplegt")
    treated_cohorts = df.loc[df["first_treat_year"] > 0, "first_treat_year"]
    dynamic_max = int(df["year"].max() - treated_cohorts.min())
    placebo_max = int(treated_cohorts.max() - df["year"].min() - 1)
    log(f"  did_multiplegt dynamic: {dynamic_max}")
    log(f"  did_multiplegt placebo: {placebo_max}")
    dcdh = sp.did_multiplegt(
        data=df,
        y="Y",
        group="unit_id",
        time="year",
        treatment="treatment",
        controls=["X1", "X2"],
        dynamic=dynamic_max,
        placebo=placebo_max,
        n_boot=100,
        seed=SEED,
    )
    log(str(dcdh))
    result_summaries.append(save_result("dcdh", dcdh))
    save_statspai_event_plot(
        dcdh,
        FIGURE_DIR / "fig07_dcdh_statspai_event_study.png",
        "did_multiplegt dynamic and placebo effects",
        "#E15759",
    )
    plot_sources["fig07_dcdh_statspai_event_study.png"] = (
        "Generated directly by dcdh.event_study_plot() from StatsPAI"
    )

    pd.DataFrame(result_summaries).to_csv(
        OUTPUT_DIR / "table_method_summary.csv", index=False
    )
    write_json(OUTPUT_DIR / "plot_sources.json", plot_sources)

    log("\nMethod summary")
    log(pd.DataFrame(result_summaries).to_string(index=False))
    log(f"\nDone. Tables: {OUTPUT_DIR.relative_to(ROOT)}")
    log(f"Done. Figures: {FIGURE_DIR.relative_to(ROOT)}")
    (OUTPUT_DIR / "run_log.txt").write_text("\n".join(LOG_LINES), encoding="utf-8")


if __name__ == "__main__":
    main()
